Na= input("请输入姓名：")
Co= input("请输入公司：")
Po= input("请输入职位：")
Ce= input("请输入电话：")
Ma= input("请输入邮箱：")
print("*"*100)
print("公司名称%s"  %Co)
print("")
print("姓名：%s"   %Na+"（职位：%s）"    %Po)
print("")
print("电话：%s"   %Ce)
print("邮箱：%s"   %Ma)
print("*"*100)
